// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvBpVFszShwVE68c0fFjJfZufvoAOugXQ',
    appId: '1:618803393691:web:272da764f3f61551eec23e',
    messagingSenderId: '618803393691',
    projectId: 'nanocraft-c0045',
    authDomain: 'nanocraft-c0045.firebaseapp.com',
    storageBucket: 'nanocraft-c0045.firebasestorage.app',
    measurementId: 'G-FNMPLWRKPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnb8cNeg8s7XsCMYh3SHLdObn889EDXQ',
    appId: '1:618803393691:android:bd46d1189601db10eec23e',
    messagingSenderId: '618803393691',
    projectId: 'nanocraft-c0045',
    storageBucket: 'nanocraft-c0045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpf7VlfwBBaxQYei2LZRLRWeAhAUX3u0',
    appId: '1:618803393691:ios:26f35904feea2923eec23e',
    messagingSenderId: '618803393691',
    projectId: 'nanocraft-c0045',
    storageBucket: 'nanocraft-c0045.firebasestorage.app',
    iosClientId: '618803393691-df5mo3i6gcbi3mqqudqn9joogektudpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanocraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpf7VlfwBBaxQYei2LZRLRWeAhAUX3u0',
    appId: '1:618803393691:ios:26f35904feea2923eec23e',
    messagingSenderId: '618803393691',
    projectId: 'nanocraft-c0045',
    storageBucket: 'nanocraft-c0045.firebasestorage.app',
    iosClientId: '618803393691-df5mo3i6gcbi3mqqudqn9joogektudpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.nanocraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvBpVFszShwVE68c0fFjJfZufvoAOugXQ',
    appId: '1:618803393691:web:4507800222f002b0eec23e',
    messagingSenderId: '618803393691',
    projectId: 'nanocraft-c0045',
    authDomain: 'nanocraft-c0045.firebaseapp.com',
    storageBucket: 'nanocraft-c0045.firebasestorage.app',
    measurementId: 'G-BGY5RQ7X5E',
  );
}
